/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TokenResponse } from '../../models/token-response';

export interface 08136088C4862C313B35D6518Bab8D3A$Params {
      body?: {

/**
 * The user's name.
 */
'name': string;

/**
 * The url to the user's avatar.
 */
'avatar_url'?: string;

/**
 * The email of the user.
 */
'email': string;

/**
 * The password for the user
 */
'password': string;
}
}

export function 08136088C4862C313B35D6518Bab8D3A(http: HttpClient, rootUrl: string, params?: 08136088C4862C313B35D6518Bab8D3A$Params, context?: HttpContext): Observable<StrictHttpResponse<TokenResponse>> {
  const rb = new RequestBuilder(rootUrl, 08136088C4862C313B35D6518Bab8D3A.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TokenResponse>;
    })
  );
}

08136088C4862C313B35D6518Bab8D3A.PATH = '/auth/register';
