/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TokenResponse } from '../../models/token-response';

export interface 99D66635C4992Aeaa6Aa44Ff653D0563$Params {
      body?: {

/**
 * The email of the user.
 */
'email': string;

/**
 * The password for the user
 */
'password': string;
}
}

export function 99D66635C4992Aeaa6Aa44Ff653D0563(http: HttpClient, rootUrl: string, params?: 99D66635C4992Aeaa6Aa44Ff653D0563$Params, context?: HttpContext): Observable<StrictHttpResponse<TokenResponse>> {
  const rb = new RequestBuilder(rootUrl, 99D66635C4992Aeaa6Aa44Ff653D0563.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TokenResponse>;
    })
  );
}

99D66635C4992Aeaa6Aa44Ff653D0563.PATH = '/auth/login';
