/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { User } from '../../models/user';

export interface F96Edb08C6F7830E1850Cde4C5B920Bc$Params {
  id: number;
}

export function f96Edb08C6F7830E1850Cde4C5B920Bc(http: HttpClient, rootUrl: string, params: F96Edb08C6F7830E1850Cde4C5B920Bc$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'data'?: User;
}>> {
  const rb = new RequestBuilder(rootUrl, f96Edb08C6F7830E1850Cde4C5B920Bc.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'data'?: User;
      }>;
    })
  );
}

f96Edb08C6F7830E1850Cde4C5B920Bc.PATH = '/comments/{id}/user';
