/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { User } from '../../models/user';

export interface 6946Bbab7898F59A09E3C8E529A38907$Params {

/**
 * id or "me"
 */
  id: number;
}

export function 6946Bbab7898F59A09E3C8E529A38907(http: HttpClient, rootUrl: string, params: 6946Bbab7898F59A09E3C8E529A38907$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'data'?: User;
}>> {
  const rb = new RequestBuilder(rootUrl, 6946Bbab7898F59A09E3C8E529A38907.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'data'?: User;
      }>;
    })
  );
}

6946Bbab7898F59A09E3C8E529A38907.PATH = '/users/{id}';
