/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Post } from '../../models/post';

export interface 86818D33Ca62De84348B16E4653636F7$Params {

/**
 * id or "me"
 */
  id: number;
}

export function 86818D33Ca62De84348B16E4653636F7(http: HttpClient, rootUrl: string, params: 86818D33Ca62De84348B16E4653636F7$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'data'?: Array<Post>;
}>> {
  const rb = new RequestBuilder(rootUrl, 86818D33Ca62De84348B16E4653636F7.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'data'?: Array<Post>;
      }>;
    })
  );
}

86818D33Ca62De84348B16E4653636F7.PATH = '/users/{id}/posts';
