/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Comment } from '../../models/comment';

export interface D1B8Dfdbeb145Eb22Cdcc439D2A6E469$Params {

/**
 * id or "me"
 */
  id: number;
}

export function d1B8Dfdbeb145Eb22Cdcc439D2A6E469(http: HttpClient, rootUrl: string, params: D1B8Dfdbeb145Eb22Cdcc439D2A6E469$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'data'?: Array<Comment>;
}>> {
  const rb = new RequestBuilder(rootUrl, d1B8Dfdbeb145Eb22Cdcc439D2A6E469.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'data'?: Array<Comment>;
      }>;
    })
  );
}

d1B8Dfdbeb145Eb22Cdcc439D2A6E469.PATH = '/users/{id}/comments';
