/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Comment {
  created_at?: string;
  id?: number;
  post_id?: number;
  text?: string;
  updated_at?: string;
  user_id?: number;
}
