/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * An error occurred with the request
 */
export interface ErrorResponse {
  exception?: string;
  message?: string;
}
