/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * This action is unauthorized
 */
export interface ForbiddenResponse {
  exception?: string;
  message?: string;
}
