/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * The resource was not found
 */
export interface NotFoundResponse {
  exception?: string;
  message?: string;
}
