/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PicturePost } from '../models/picture-post';
import { TextPost } from '../models/text-post';
import { VideoPost } from '../models/video-post';
export interface Post {
  content?: (PicturePost | VideoPost | TextPost);
  created_at?: string;
  id?: number;
  like_count?: number;
  updated_at?: string;
  user_id?: number;
}
