/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * The API token for the user
 */
export interface TokenResponse {
  data?: {
'token'?: string;
};
}
