/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface User {
  avatar_url?: string;
  created_at?: string;
  email?: string;
  id?: number;
  name?: string;
  updated_at?: string;
}
