/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ValidationErrorsArrayItem } from '../models/validation-errors-array-item';

/**
 * The post data was in invalid format
 */
export interface ValidationErrorResponse {
  errors?: {
'string'?: Array<ValidationErrorsArrayItem>;
};
  message?: string;
}
