/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { User } from '../../models/user';

export interface 1B6008A78E66Ebbbb7A959Cf4B614C5E$Params {
  id: number;
}

export function 1B6008A78E66Ebbbb7A959Cf4B614C5E(http: HttpClient, rootUrl: string, params: 1B6008A78E66Ebbbb7A959Cf4B614C5E$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'data'?: User;
}>> {
  const rb = new RequestBuilder(rootUrl, 1B6008A78E66Ebbbb7A959Cf4B614C5E.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'data'?: User;
      }>;
    })
  );
}

1B6008A78E66Ebbbb7A959Cf4B614C5E.PATH = '/posts/{id}/user';
