/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Post } from '../../models/post';

export interface 383098504Fbc54F89F2165Fe512Da03C$Params {

/**
 * A POSIX timestamp from the last moment data was polled
 */
  since: number;
}

export function 383098504Fbc54F89F2165Fe512Da03C(http: HttpClient, rootUrl: string, params: 383098504Fbc54F89F2165Fe512Da03C$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'data'?: Array<Post>;
}>> {
  const rb = new RequestBuilder(rootUrl, 383098504Fbc54F89F2165Fe512Da03C.PATH, 'get');
  if (params) {
    rb.query('since', params.since, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'data'?: Array<Post>;
      }>;
    })
  );
}

383098504Fbc54F89F2165Fe512Da03C.PATH = '/posts/poll';
