/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface 448633Fd8A928Fd1508D9E6Ee74322C7$Params {
  id: number;
}

export function 448633Fd8A928Fd1508D9E6Ee74322C7(http: HttpClient, rootUrl: string, params: 448633Fd8A928Fd1508D9E6Ee74322C7$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, 448633Fd8A928Fd1508D9E6Ee74322C7.PATH, 'delete');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

448633Fd8A928Fd1508D9E6Ee74322C7.PATH = '/posts/{id}/likes';
