/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Post } from '../../models/post';

export interface 6B9Af649206Ee145Dfc5584522C37327$Params {
  id: number;
}

export function 6B9Af649206Ee145Dfc5584522C37327(http: HttpClient, rootUrl: string, params: 6B9Af649206Ee145Dfc5584522C37327$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'data'?: Post;
}>> {
  const rb = new RequestBuilder(rootUrl, 6B9Af649206Ee145Dfc5584522C37327.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'data'?: Post;
      }>;
    })
  );
}

6B9Af649206Ee145Dfc5584522C37327.PATH = '/posts/{id}';
