/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { User } from '../../models/user';

export interface B43C615B6698B2F011A40A722089Ad16$Params {
  id: number;
}

export function b43C615B6698B2F011A40A722089Ad16(http: HttpClient, rootUrl: string, params: B43C615B6698B2F011A40A722089Ad16$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'data'?: Array<User>;
}>> {
  const rb = new RequestBuilder(rootUrl, b43C615B6698B2F011A40A722089Ad16.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'data'?: Array<User>;
      }>;
    })
  );
}

b43C615B6698B2F011A40A722089Ad16.PATH = '/posts/{id}/likes';
