/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Comment } from '../../models/comment';

export interface Bd0379A97B4057F7D5A720A565E8Bf19$Params {
  id: number;
}

export function bd0379A97B4057F7D5A720A565E8Bf19(http: HttpClient, rootUrl: string, params: Bd0379A97B4057F7D5A720A565E8Bf19$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'data'?: Array<Comment>;
}>> {
  const rb = new RequestBuilder(rootUrl, bd0379A97B4057F7D5A720A565E8Bf19.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'data'?: Array<Comment>;
      }>;
    })
  );
}

bd0379A97B4057F7D5A720A565E8Bf19.PATH = '/posts/{id}/comments';
