/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Post } from '../../models/post';

export interface Ccc642D639Ab35E23161Fa8D2F37A9A3$Params {
      body?: {

/**
 * The type of the comment
 */
'type': 'text' | 'video' | 'picture';

/**
 * The content of the comment
 */
'text': string;

/**
 * The url to the video; if post is of type video
 */
'video_url'?: string;

/**
 * The url to the picture; if post is of type picture
 */
'picture_url'?: string;
}
}

export function ccc642D639Ab35E23161Fa8D2F37A9A3(http: HttpClient, rootUrl: string, params?: Ccc642D639Ab35E23161Fa8D2F37A9A3$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'data'?: Post;
}>> {
  const rb = new RequestBuilder(rootUrl, ccc642D639Ab35E23161Fa8D2F37A9A3.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'data'?: Post;
      }>;
    })
  );
}

ccc642D639Ab35E23161Fa8D2F37A9A3.PATH = '/posts';
