/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Post } from '../../models/post';

export interface Cce7863441436Fd49Dc474491F658292$Params {
  cursor?: string;
}

export function cce7863441436Fd49Dc474491F658292(http: HttpClient, rootUrl: string, params?: Cce7863441436Fd49Dc474491F658292$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'data'?: Array<Post>;

/**
 * The URL to the current page
 */
'path'?: string;

/**
 * The cursor for the next page
 */
'next_cursor'?: string;

/**
 * The URL to the next page.
 */
'next_page_url'?: string;

/**
 * The cursor for the previous page
 */
'prev_cursor'?: string;

/**
 * The URL to the previous page
 */
'prev_page_url'?: string;
}>> {
  const rb = new RequestBuilder(rootUrl, cce7863441436Fd49Dc474491F658292.PATH, 'get');
  if (params) {
    rb.query('cursor', params.cursor, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'data'?: Array<Post>;
      
      /**
       * The URL to the current page
       */
      'path'?: string;
      
      /**
       * The cursor for the next page
       */
      'next_cursor'?: string;
      
      /**
       * The URL to the next page.
       */
      'next_page_url'?: string;
      
      /**
       * The cursor for the previous page
       */
      'prev_cursor'?: string;
      
      /**
       * The URL to the previous page
       */
      'prev_page_url'?: string;
      }>;
    })
  );
}

cce7863441436Fd49Dc474491F658292.PATH = '/posts';
