/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Comment } from '../../models/comment';

export interface Fae30Daa3987C576D9Dd4709119D26Da$Params {
  id: number;
      body?: {

/**
 * The content of the comment
 */
'text': string;
}
}

export function fae30Daa3987C576D9Dd4709119D26Da(http: HttpClient, rootUrl: string, params: Fae30Daa3987C576D9Dd4709119D26Da$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'data'?: Comment;
}>> {
  const rb = new RequestBuilder(rootUrl, fae30Daa3987C576D9Dd4709119D26Da.PATH, 'post');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'data'?: Comment;
      }>;
    })
  );
}

fae30Daa3987C576D9Dd4709119D26Da.PATH = '/posts/{id}/comments';
