/**
 * Expivi Twitter API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Comment { 
    id?: number;
    user_id?: number;
    post_id?: number;
    text?: string;
    created_at?: string;
    updated_at?: string;
}

