/**
 * Expivi Twitter API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Post } from './post';


export interface ListPosts200Response { 
    data?: Array<Post>;
    /**
     * The URL to the current page
     */
    path?: string;
    /**
     * The cursor for the next page
     */
    next_cursor?: string;
    /**
     * The URL to the next page.
     */
    next_page_url?: string;
    /**
     * The cursor for the previous page
     */
    prev_cursor?: string;
    /**
     * The URL to the previous page
     */
    prev_page_url?: string;
}

