/**
 * Expivi Twitter API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PicturePost { 
    type?: PicturePost.TypeEnum;
    text?: string;
    picture_url?: string;
}
export namespace PicturePost {
    export type TypeEnum = 'picture';
    export const TypeEnum = {
        Picture: 'picture' as TypeEnum
    };
}


