/**
 * Expivi Twitter API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PostContent } from './postContent';


export interface Post { 
    id?: number;
    user_id?: number;
    like_count?: number;
    created_at?: string;
    updated_at?: string;
    content?: PostContent;
}

