/**
 * Expivi Twitter API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PicturePost } from './picturePost';
import { VideoPost } from './videoPost';
import { TextPost } from './textPost';


/**
 * @type PostContent
 * @export
 */
export type PostContent = PicturePost | TextPost | VideoPost;

