/**
 * Expivi Twitter API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RegisterUserRequest { 
    /**
     * The user\'s name.
     */
    name: string;
    /**
     * The url to the user\'s avatar.
     */
    avatar_url?: string;
    /**
     * The email of the user.
     */
    email: string;
    /**
     * The password for the user
     */
    password: string;
}

