/**
 * Expivi Twitter API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TokenResponseData } from './tokenResponseData';


/**
 * The API token for the user
 */
export interface TokenResponse { 
    data?: TokenResponseData;
}

