/**
 * Expivi Twitter API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ValidationErrorResponseErrors } from './validationErrorResponseErrors';


/**
 * The post data was in invalid format
 */
export interface ValidationErrorResponse { 
    message?: string;
    errors?: ValidationErrorResponseErrors;
}

