/**
 * Expivi Twitter API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface VideoPost { 
    type?: VideoPost.TypeEnum;
    text?: string;
    video_url?: string;
}
export namespace VideoPost {
    export type TypeEnum = 'video';
    export const TypeEnum = {
        Video: 'video' as TypeEnum
    };
}


