/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { Comment } from './models/comment';
export type { ErrorResponse } from './models/error-response';
export type { ForbiddenResponse } from './models/forbidden-response';
export type { NotFoundResponse } from './models/not-found-response';
export type { PicturePost } from './models/picture-post';
export type { Post } from './models/post';
export type { TextPost } from './models/text-post';
export type { TokenResponse } from './models/token-response';
export type { UnauthorizedResponse } from './models/unauthorized-response';
export type { User } from './models/user';
export type { ValidationErrorResponse } from './models/validation-error-response';
export type { ValidationErrorsArrayItem } from './models/validation-errors-array-item';
export type { VideoPost } from './models/video-post';
